### ISSUE TITLE
An issue about the file name: 00_BF.csv

### ISSUE THREAD

**Issue by shana34** [ROCm/Tensile#1162]
![image](https://user-images.githubusercontent.com/22281195/92900261-1d0b5900-f452-11ea-991d-66adcbd2a2b2.png)
I am using tensile-master-3.3 with rocm-3.3.1. Firstly, tensile did not found 'llvm-config', so I manusally add the path in '.bashrc'
![image](https://user-images.githubusercontent.com/22281195/92899772-b0905a00-f451-11ea-92d7-d90bb4a0813c.png)
![image](https://user-images.githubusercontent.com/22281195/92900779-8d19df00-f452-11ea-9058-4fbbfe6e21ce.png)
Then, I get such a different issue, which tell me did not find the '00_BF-new.csv' where itself build a file named '00_BF.csv' as shown above. 
I wonder how to solve this question, thx.

**Comment by shana34** [comment]
I tried to rename the file as '00_BF-new.csv'. However, this does not settle the problem.

**Comment by ppanchad-amd** [comment]
@shana34 Apologies for the lack of response.  Can you please test with the latest ROCm 6.1.2? If issue does not occur, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@shana34 Closing ticket. Please re-open the ticket if you still see the issue with the latest ROCm. Thanks!
