### ISSUE TITLE
Add Navi GFX1010 support

### ISSUE THREAD

**Issue by rigtorp** [ROCm/Tensile#1165]
I was able to build rocBLAS for GFX1010 by adding "gfx1010" to this list:
https://github.com/ROCmSoftwarePlatform/Tensile/blob/79f2eaec38754e4c0acf3399710f68d2b8586450/Tensile/TensileCreateLibrary.py#L1262

https://github.com/ROCmSoftwarePlatform/pytorch/issues/718
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1106

**Comment by tuxbotix** [comment]
Works and tests running happily (using the GPU) for rocBLAS (after adding archs to it too) :D, using Tensile & rocBLAS branch gfx10

**Comment by rigtorp** [comment]
Any update on officially enabling gfx1010? @wbgilmartin @benjaminulmer

**Comment by Daasin** [comment]
I would also be interested in any updates for GFX10xx :3

**Comment by Daasin** [comment]
I would also be interested in any updates for GFX10xx :3

**Comment by cgmb** [comment]
gfx1010 has been enabled by default in rocBLAS builds since ROCm 4.3.0. https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/rocm-4.3.0/CMakeLists.txt#L169

**Comment by B0-B** [comment]
Any updates wether someone build pytorch with gfx1010?

**Comment by ppanchad-amd** [comment]
@rigtorp GFX 1010 is not supported in the latest ROCm 6.1.2 Thanks!
