### ISSUE TITLE
hipblasdgemm not getting close to peak

### ISSUE THREAD

**Issue by JorgeG94** [ROCm/Tensile#1705]
### What is the expected behavior
- I would expect a dgemm of sizeable input to achieve close to the 47.9 TFLOP/s 

### What actually happens
- By using the code provided in: https://github.com/JorgeG94/calum_performance_tool it can be seen that rocm/5.4.0 produces 38TFLOP/s 

### How to reproduce
- The code in the repo https://github.com/JorgeG94/calum_performance_tool has the readme, but basically: 
`hipcc -L/opt/rocm-5.4.3/lib -lhipblas --offload-arch=gfx90a performance.cpp`
`./a.out 36000 14400 36000 10 T T`

### Environment
| Hardware | description |
|-----|-----|
| GPU | MI250x |
| CPU | AMD Optimized 3rd Gen EPYC|

| Software | version |
|-----|-----|
| ROCM | v5.4.0 |

**Comment by nakajee** [comment]
I will check this on my side.
Does the performance drop happen only with this size?
Have you checked other sizes and/or orientations?

**Comment by ppanchad-amd** [comment]
@JorgeG94 Can you please test with the latest ROCm 6.1.2? If your issue is resolved, please close the ticket. Thanks!

**Comment by schung-amd** [comment]
Hi @JorgeG94, are you still experiencing this issue? If so, can you answer @nakajee's questions?

**Comment by JorgeG94** [comment]
hi! sorry about this life was very chaotic. Moving to a newer version and some driver updates helped a lot thanks!
