### ISSUE TITLE
how to enable t_debug?

### ISSUE THREAD

**Issue by jdgh000** [ROCm/Tensile#1722]
I am seeing lot of T_Debug which enables number of debug prints. However I am at loss to how to enable it from cmdline param? 
I see there is rv=kernelArguments(T_debug) but it is unclear how to pass this onto API.
There are other cmdline args i.e. TENSILE_DB which I can easily figure out and enable add'l debug prints but not with T_debug.

**Comment by ppanchad-amd** [comment]
@jdgh000 Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
Hi @jdgh000. Closing ticket due to lack of activity. Please re-open ticket if you still need assistance. Thanks!
