### ISSUE TITLE
kernel.cpp without assembly kernel implement

### ISSUE THREAD

**Issue by DoubleClark** [ROCm/Tensile#1832]
os: Ubuntu20.04
rocm：5.7.1
gpu: AMD MI210 gfx90a
tensile_version: Tensile 4.38.0 for ROCm 5.7.1

Hello,
could you please to give an example about how to generate the assembly kernel code in Tensile, the generation of kernel library [*.hsaco] is success, but when i check the kernel.cpp file in ./1_BenchmarkProblems/Cijk_Ailk_Bljk_HHS_BH_00/00_Final/source/Kernels.cpp, there is no GEMM kernel implement, only some kernel like Cijk_H_PostGSU, which not looks like GEMM kernel .

I use the offical config file and command line shown as below for assembly kernel generation，
../Tensile/bin/Tensile ../Tensile/Configs/rocblas_hpa_hgemm_nn_inc1_asm_full.yaml ./

Besides, when i try to generate source code, run command line below, everything seems normal.
../Tensile/bin/Tensile ../Tensile/Configs/rocblas_hpa_hgemm_hip_lite_v1.yaml ./

Q1:Does Tensile support generate assembly kernel? If support, may i get one example config file?
i try to use the asm_new.sh to generate the .s file,  i suppose this is the asm file i need, but do we have a guide about how to use this file 

Thansk for your help and experience.

**Comment by nakajee** [comment]
You can find many Tensile config yaml files for asm kernels under Tensile/Tests.
You can find files with "asm" for asm kernels.

**Comment by ppanchad-amd** [comment]
@DoubleClark Do you still need assistance with this ticket? If not, please close the ticket. Thanks!
