### ISSUE TITLE
undefined symbol: Tensile::TypedContractionInputs<Tensile::Half>::TypedContractionInputs()

### ISSUE THREAD

**Issue by xiakubaobaore** [ROCm/Tensile#1833]
cmake libTensileHost.a by -DTensile_LIBRARY_FORMAT="msgpack" -DCMAKE_CXX_COMPILER="hipcc".
at datatype=half problem, use "TypedContractionInputs<Half> deviceInputs;" init input, then fill data with "deviceInputs.a = reinterpret_cast<Tensile::Half*>(d_A);" and "d_A"is "half *". 
then error occur: 
ld.lld: error: undefined symbol: Tensile::TypedContractionInputs<Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half>::TypedContractionInputs()
ld.lld: error: undefined symbol: Tensile::TypedContractionInputs<Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half, Tensile::Half>::~TypedContractionInputs()
assume it means the "TypedContractionInputs<Half>" has no Constructor? but the non-parameter constructor is default generated?

**Comment by sparklesea** [comment]
I encountered the same problem, changing TypedContractionInputs to <_Float16, _Float16, _Float16, _Float16, float, float> will pass compilation, but errors are still reported at run time: Segmentation fault (core dumped).

**Comment by ppanchad-amd** [comment]
@xiakubaobaore Apologies for the lack of response. Can you please test with the latest ROCm 6.1.2? If issue is resolved, please close the ticket. Thanks!

**Comment by huanrwan-amd** [comment]
@xiakubaobaore, @sparklesea can you please share the sample code and steps for us to reproduce the issue? and please also provide information on the hardware and software version you guys are working on. Thanks.

**Comment by huanrwan-amd** [comment]
@xiakubaobaore, @sparklesea. closed the issue for no updates for 3 weeks. If you would like us to investigate further, please leave comments.
