### ISSUE TITLE
[Feature]: Generalize linux distro handling

### ISSUE THREAD

**Issue by trixirt** [ROCm/Tensile#1969]
### Suggestion Description

Fedora packages ROCm to system locations.  Not /opt/rocm.
When ROCm tools are not found in /opt/rocm, they should be searched for in other locations. 

### Operating System

Fedora Rawhide

### GPU

ALL

### ROCm Component

ALL

**Comment by tcgu-amd** [comment]
Hi @trixirt, thanks for reaching out! Is this request pertaining to a specific part of Tensile? If so, could you specify it? Or is it a more general request for the entirety of ROCm? Thanks!

**Comment by trixirt** [comment]
At least Fedora and Debian have in-distro ROCm support.  Tensile does not work as-is for anything but the AMD build of Tensile.

**Comment by ellosel** [comment]
@trixirt a few quick questions:

1. Have you tried using the `ROCM_PATH` environment variable?
2. If so, presumably it failed so what were the deficiencies in the environment variable?
3. Can you share a docker file to reproduce?

**Comment by trixirt** [comment]
I am no asking for myself, I am asking for the normal user. I know that locally i can touch many env variables that will give me a good result, but I am aware of the env variables.  The normal user will expect it to just work, that is the default values are meaningful.   When Tensile is used without first installing the AMD ROCm, the default values are wrong, nothing is in /opt/rocm, nor is llvm/bin part of any clang path.

**Comment by ellosel** [comment]
Please provide a dockerfile so we can reproduce.

**Comment by tcgu-amd** [comment]
Hi @trixirt, unfortunately, we do not plan on supporting this feature for now. Please see this  https://github.com/ROCm/Tensile/pull/1971#issuecomment-2444912900 for more details. Thanks!
