### ISSUE TITLE
[Issue]:  How is a decision tree type YAML trained?

### ISSUE THREAD

**Issue by lty-qd** [ROCm/Tensile#1975]
### Problem Description

Based on the decision tree used in the Test to select a kernel, I want to see how the features in the YAML file are trained.

### Operating System

Centos

### CPU

AMD

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

**Comment by bstefanuk** [comment]
@lty-qd Thanks for submitting. 

Unfortunately, we need more context than is provided in your ticket to provide a meaningful solution. 

I recommend adding the following details to the description:
1. Detailed steps to reproduce
2. Current output
3. Desired output

**Comment by ppanchad-amd** [comment]
Hi @lty-qd. Do you still need assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
Hi @lty-qd.  Closing ticket due to lack of activity. Please comment if you still require assistance with the additional requested details. Thanks!

**Comment by lty-qd** [comment]
"Sorry for the late reply, I just saw this email. Thank you for your response. Currently, Tensile does not support decision tree-based training, right? I couldn't find the specific details in the code."

| |
lty_personal
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/13/2024 00:28 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ROCm/Tensile] [Issue]: How is a decision tree type YAML trained? (Issue #1975) |

Hi @lty-qd. Closing ticket due to lack of activity. Please comment if you still require assistance with the additional requested details. Thanks!
