### ISSUE TITLE
[Feature]: Offload compression

### ISSUE THREAD

**Issue by LunNova** [ROCm/Tensile#2031]
### Suggestion Description

TensileCreateLibrary should support offload compression.

rocBLAS uses TensileCreateLibrary and can hit 3GB of hsaco, co and dat/yaml files under `lib/rocblas/library/`.

Compressing each file individually with zstd reduces this to ~150MB. Compressing everything into a single archive with 7zip reduces this to 70MB.

clang-offload-bundler and clang --offload-arch=... already support compression with `--compress` and `--offload-compress` flags.

rocBLAS tries to compress its kernels with these options https://github.com/ROCm/rocBLAS/commit/bb81a8337ddd3ecc20f252eb0135cb8d58e2eabd but it barely does anything because most space is used by tensile which unbundles libraries.

### Operating System

N/A

### GPU

N/A

### ROCm Component

Tensile

**Comment by bstefanuk** [comment]
Good issue, thanks for raising this request @LunNova. This is something we would like to implement. I've noted your comments and will post any updates here.

**Comment by bstefanuk** [comment]
Assembly object compression added in #2054, closing this issue.

**Comment by LunNova** [comment]
Awesome! Thanks @bstefanuk 

Before:
```
$ du -h -d 1 (nix build --print-out-paths --no-link .#rocmPackages.rocblas) | sort -hr
3.3G    /nix/store/hnvb75kvaq7a2jlqkx7x6jzm3f5iaxnr-rocblas-6.3.0/lib
3.3G    /nix/store/hnvb75kvaq7a2jlqkx7x6jzm3f5iaxnr-rocblas-6.3.0
2.9M    /nix/store/hnvb75kvaq7a2jlqkx7x6jzm3f5iaxnr-rocblas-6.3.0/include
12K     /nix/store/hnvb75kvaq7a2jlqkx7x6jzm3f5iaxnr-rocblas-6.3.0/share
```

After:
```
$ du -h -d 1 (nix build --print-out-paths --no-link .#rocmPackages.rocblas) | sort -hr
trace: gfx908;gfx90a;gfx942;gfx1030;gfx1100
723M    /nix/store/bplzavacsrjsg4i2ryc1cbqfzxx7caz3-rocblas-6.3.0
720M    /nix/store/bplzavacsrjsg4i2ryc1cbqfzxx7caz3-rocblas-6.3.0/lib
2.9M    /nix/store/bplzavacsrjsg4i2ryc1cbqfzxx7caz3-rocblas-6.3.0/include
12K     /nix/store/bplzavacsrjsg4i2ryc1cbqfzxx7caz3-rocblas-6.3.0/share
```

4.5x compression factor for the whole library with `"gfx908" "gfx90a" "gfx942" "gfx1030" "gfx1100"` as targets.

**Comment by LunNova** [comment]
Would you accept a PR to apply zstd compression to the msgpack files?
