### ISSUE TITLE
[Question] How does tensile avoid bank conflict for matrix core instructions?

### ISSUE THREAD

**Issue by LeiWang1999** [ROCm/Tensile#2043]
### Problem Description

Hi guys, thanks for this awesome work!

Notice that Tensile applies some rules to avoid bank conflict (from omniperf/rocprof reports), These rules can be identified in the kernel name that we extract from the rocblas GEMM kernel, such as:

```bash
Cijk_Alik_Bljk_HHS_BH_MT128x96x64_MI32x32x8x1_SE_1LDSB1_APM1_ABV0_ACED0_AF0EM8_AF1EM1_AMAS3_ASE_ASGT_ASLT_ASAE01_ASCE01_ASEM1_AAC0_BL1_BS1_DTL0_DTVA0_DVO0_ETSP_EPS0_FSSC10_FL0_GRPM1_GRVW8_GSU1_GSUAMB_GLS0_ISA90a_IU1_K1_KLA_LBSPP128_LPA8_LPB8_LDL1_LRVW8_LWPMn1_LDW0_MAC_MIAV0_MDA2_MO40_MMFGLC_NTA0_NTB0_NTC0_NTD0_NEPBS0_NLCA1_NLCB1_ONLL1_OPLV0_PK0_PAP0_PGR2_PLR9_RK0_SIA3_SS0_SU32_SUM0_SUS128_SCIUI1_SPO0_SRVW4_SSO0_SVW4_SNLL0_TSGRA0_TSGRB0_TT1_96_TLDS1_UMLDSA1_UMLDSB1_USFGROn1_VAW2_VSn1_VW2_WSGRA1_WSGRB1_WS64_WG128_2_1_WGM15
```

From this kernel name, we can infer that certain memory access patterns may involve padding or other transformations, potentially even XOR-based rules, to optimize for memory efficiency.

Is there any documentation or code that describes these transformation rules in detail (as we are try to enhance the performance from hip side)? For example, in NVIDIA’s documentation, they provide XOR-based expressions that clarify their memory transformation logic:

<img width="422" alt="image" src="https://github.com/user-attachments/assets/ec9ba8c2-c08c-4e06-af30-9fe6b29c3669">

Thanks :)

### Operating System

Ubuntu 20.04

### CPU

AMD

### GPU

MI 250

### ROCm Version

ROCm 6.2.2

**Comment by ppanchad-amd** [comment]
Hi @LeiWang1999. Internal ticket has been created to assist with your issue. Thanks!

**Comment by schung-amd** [comment]
See https://github.com/ROCm/composable_kernel/issues/1603.
