### ISSUE TITLE
[Issue]: gfx1151 removed from 6.3

### ISSUE THREAD

**Issue by trixirt** [ROCm/Tensile#2059]
### Problem Description

In 6.2.4, support for gfx1151 was added ex/
https://github.com/ROCm/Tensile/blob/release/rocm-rel-6.2/Tensile/AsmCaps.py#L774

In 6.3.0, it has been removed
https://github.com/ROCm/Tensile/blob/release/rocm-rel-6.3/Tensile/AsmCaps.py#L774

In develop, it is here
https://github.com/ROCm/Tensile/blob/develop/Tensile/AsmCaps.py#L774

### Operating System

Fedora Rawhide

### CPU

ALL

### GPU

ALL

### ROCm Version

ROCm 6.3.0

**Comment by trixirt** [comment]
I do not need an immediate fix.  I was able to cherry pick the commit from the 6.2 branch and building gfx1151 rocblas looks ok.  This will show up in Fedora Rawhide soon.

**Comment by trixirt** [comment]
Here is the cherry picked from 6.2.4 tag
https://src.fedoraproject.org/rpms/python-tensile/blob/rawhide/f/0001-Adding-gfx1151-to-6.2-2026.patch
And how it is applied in the spec file
https://src.fedoraproject.org/rpms/python-tensile/blob/rawhide/f/python-tensile.spec#_24

**Comment by bstefanuk** [comment]
Hi @trixirt we will cherry pick the gfx1151 support commit into release/rocm-rel-6.3 through the proper channel in the coming days. I will update back here once the cherry pick is complete. Until then, as @darren-amd mentioned, I would recommend using the 6.2 release branch or the latest develop commit. 

Let me know if you run into any issues.

**Comment by trixirt** [comment]
Rawhide is a rolling release, we will pick up the change in 6.3.1 or whenever it lands, so what you are proposing if fine.

**Comment by darren-amd** [comment]
Hi @trixirt,

The changes have been cherry picked into the 6.3 branch: https://github.com/ROCm/Tensile/commit/5838cf77c4554fcdd18fe633027f4c5d69c2f656. Thanks for reporting!

**Comment by trixirt** [comment]
Thanks!
